version: "3.3"
services:
  eventstream-nginx:
    image: emrantalukder/eventstream-nginx:latest
    ports:
      - "8080:80"
    networks:
      - eventstreamnet
  eventstream-transform:
    image: emrantalukder/eventstream-transform:latest
    deploy:
      replicas: 2
    volumes:
      - ./eventstream-transform/data:/app/data
    environment:
      - "GUNICORN_WORKERS=2"
      - "ELASTICSEARCH_URL=http://elasticsearch2:9200"
    ports:
      - "9000:80"
    networks:
      - eventstreamnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    deploy:
      replicas: 1
    environment:
      - "cluster.name=docker-cluster"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "node.master=true"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - eventstreamnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    deploy:
      replicas: 2
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    networks:
      - eventstreamnet
  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.5.4'
    ports:
      - "5601:5601"
    networks:
      - eventstreamnet
networks:
  eventstreamnet: